twist_mux:
  ros__parameters:
    topics:
      safety:
        topic: "/cmd_vel_safety"
        timeout: 0.2
        priority: 255
      joystick:
        topic: "/cmd_vel_joy"
        timeout: 0.5
        priority: 100
      navigation:
        topic: "/cmd_vel_auto"
        timeout: 0.5
        priority: 10
