# config/twist_mux.yaml

# kobuki用
twist_mux_node:
  ros__parameters:
    topics:
      joystick:
        topic:   "cmd_vel_joy"
        timeout: 0.5
        priority: 100  # 👈 優先度「高」：ハンコン
      navigation:
        topic:   "cmd_vel_auto"
        timeout: 0.5
        priority: 10   # 👈 優先度「低」：自動走行
 